version: '2'

services:
  master:
    build: ./hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
  db:
    image: mysql
    container_name: "db"
    command: mysqld --user=root --verbose
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/data

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: retaildb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
  slave1:
    build: ./hadoop-slave
    container_name: "slave1"
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    build: ./hadoop-slave
    container_name: "slave2"
    ports:
      - "9902:9864"
      - "8042:8042"
  slave3:
    build: ./hadoop-slave
    container_name: "slave3"
    ports:
      - "9903:9864"
      - "8043:8042"
volumes:
    db_data:
